---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at <https://ds202-at-isu.github.io/labs.html> for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.

All submissions to the github repo will be automatically uploaded for grading once the due date is passed. Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

# Answers

This is a line from RStudio - Akshat

This is a line from rStudio - Jamey

This is a line from rStudio- Ashlynn
=======
# Experience Notes

Akshat's Notes:

12.2 - This step was easy as all it required was to go to the announcement. I created our team repo and then moved onto the next steps.

12.3 - I ran into an issue while doing this step so I just used the terminal to clone the repo onto my device using git clone instead.

12.4 - This step was easy as I found the commit and push buttons from the Rstudio Git view

12.5 - This step went smoothly as the push button confirmed my push.

12.6 - This step was the best as I was happy to see my changes represented in the repo. I look forward to creating larger more exciting projects as time continues.

Overall: This was a fun experience and I would like to continue to get better at working with Git and collaborative programming. I did not run into problems on my device however team members had an issue on theirs and we learned to use the terminal to clone and commit with Git.

12.2 - This step was easy because my teammate made the repo.

12.3 - I am used to cloning so I didn't have trouble.

12.4 - I pulled and pushed a line pretty easily from the terminal.

12.5 - Pushing was easy from the terrminal.

12.6 - I was able to look at the main repo in Github and confirm my push alongside my teammates.

12.7 - I don't want to delete the repo yet but I know how to.

Jamey: It was good to practice Git again. Some team members had issues and it was fun helping others lol

